const examForm = document.getElementById('examForm');
const resultDiv = document.getElementById('result');
const errorDiv = document.getElementById('error');
const errorMessage = document.getElementById('errorMessage');
const branchDisplay = document.getElementById('branch');
const semesterDisplay = document.getElementById('semester');
const rollNumberDisplay = document.getElementById('rollNumberDisplay');
const subjectDisplay = document.getElementById('subject');
const examTimeDisplay = document.getElementById('examTime');
const datedisplay=document.getElementById('Date');
const roomNumberDisplay = document.getElementById('roomNumber');
const blockdisplay=document.getElementById('block');
const wingDisplay = document.getElementById('wing');
const floordisplay=document.getElementById('floor');
const departmentDisplay = document.getElementById('department');


// Dummy data
const students = [
    { 
        rollNumber: 'S221306001', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Electical Network Analysis', 
        examTime: '10:00 AM', 
        date:'03/06/2024',
        roomNumber: 'A101',
        block:'1',
        wing: 'A',
        floor:'Ground Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306002', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Electical Network Analysis', 
        examTime: '10:00 AM', 
        date:'03/06/2024',
        roomNumber: 'A101',
        block:'1',
        wing: 'A',
        floor:'Ground Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306003', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Electical Network Analysis', 
        examTime: '10:00 AM', 
        date:'03/06/2024',
        roomNumber: 'A101',
        block:'1',
        wing: 'A',
        floor:'Ground Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306004', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Electical Network Analysis', 
        examTime: '10:00 AM', 
        date:'03/06/2024',
        roomNumber: 'A101',
        block:'1',
        wing: 'A',
        floor:'Ground Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306005', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Electical Network Analysis', 
        examTime: '10:00 AM', 
        date:'03/06/2024',
        roomNumber: 'A101',
        block:'1',
        wing: 'A',
        floor:'Ground Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306006', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Electical Network Analysis', 
        examTime: '10:00 AM', 
        date:'03/06/2024',
        roomNumber: 'A101',
        block:'1',
        wing: 'A',
        floor:'Ground Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306007', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Electical Network Analysis', 
        examTime: '10:00 AM', 
        date:'03/06/2024',
        roomNumber: 'A101',
        block:'1',
        wing: 'A',
        floor:'Ground Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306008', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Electical Network Analysis', 
        examTime: '10:00 AM', 
        date:'03/06/2024',
        roomNumber: 'A101',
        block:'1',
        wing: 'A',
        floor:'Ground Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306009', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Electical Network Analysis', 
        examTime: '10:00 AM', 
        date:'03/06/2024',
        roomNumber: 'A101',
        block:'1',
        wing: 'A',
        floor:'Ground Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306010', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Electical Network Analysis', 
        examTime: '10:00 AM', 
        date:'03/06/2024',
        roomNumber: 'A101',
        block:'1',
        wing: 'A',
        floor:'Ground Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306011', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Electical Network Analysis', 
        examTime: '10:00 AM', 
        date:'03/06/2024',
        roomNumber: 'A101',
        block:'1',
        wing: 'A',
        floor:'Ground Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306012', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Electical Network Analysis', 
        examTime: '10:00 AM', 
        date:'03/06/2024',
        roomNumber: 'A101',
        block:'1',
        wing: 'A',
        floor:'Ground Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306013', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Electical Network Analysis', 
        examTime: '10:00 AM', 
        date:'03/06/2024',
        roomNumber: 'A101',
        block:'1',
        wing: 'A',
        floor:'Ground Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306014', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Electical Network Analysis', 
        examTime: '10:00 AM', 
        date:'03/06/2024',
        roomNumber: 'A101',
        block:'1',
        wing: 'A',
        floor:'Ground Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306015', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Electical Network Analysis', 
        examTime: '10:00 AM', 
        date:'03/06/2024',
        roomNumber: 'A101',
        block:'1',
        wing: 'A',
        floor:'Ground Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306016', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Electical Network Analysis', 
        examTime: '10:00 AM', 
        date:'03/06/2024',
        roomNumber: 'A101',
        block:'1',
        wing: 'A',
        floor:'Ground Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306017', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Electical Network Analysis', 
        examTime: '10:00 AM', 
        date:'03/06/2024',
        roomNumber: 'A101',
        block:'1',
        wing: 'A',
        floor:'Ground Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306018', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Electical Network Analysis', 
        examTime: '10:00 AM', 
        date:'03/06/2024',
        roomNumber: 'A101',
        block:'1',
        wing: 'A',
        floor:'Ground Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306019', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Electical Network Analysis', 
        examTime: '10:00 AM', 
        date:'03/06/2024',
        roomNumber: 'A101',
        block:'1',
        wing: 'A',
        floor:'Ground Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306020', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Electical Network Analysis', 
        examTime: '10:00 AM', 
        date:'03/06/2024',
        roomNumber: 'A101',
        block:'1',
        wing: 'A',
        floor:'Ground Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306021', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Electical Network Analysis', 
        examTime: '10:00 AM', 
        date:'03/06/2024',
        roomNumber: 'A101',
        block:'1',
        wing: 'A',
        floor:'Ground Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306022', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Electical Network Analysis', 
        examTime: '10:00 AM', 
        date:'03/06/2024',
        roomNumber: 'A101',
        block:'1',
        wing: 'A',
        floor:'Ground Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306023', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Electical Network Analysis', 
        examTime: '10:00 AM', 
        date:'03/06/2024',
        roomNumber: 'A101',
        block:'1',
        wing: 'A',
        floor:'Ground Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306024', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Electical Network Analysis', 
        examTime: '10:00 AM', 
        date:'03/06/2024',
        roomNumber: 'A101',
        block:'1',
        wing: 'A',
        floor:'Ground Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306025', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Electical Network Analysis', 
        examTime: '10:00 AM', 
        date:'03/06/2024',
        roomNumber: 'A101',
        block:'1',
        wing: 'A',
        floor:'Ground Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306026', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Electical Network Analysis', 
        examTime: '10:00 AM', 
        date:'03/06/2024',
        roomNumber: 'A101',
        block:'1',
        wing: 'A',
        floor:'Ground Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306027', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Electical Network Analysis', 
        examTime: '10:00 AM', 
        date:'03/06/2024',
        roomNumber: 'A101',
        block:'1',
        wing: 'A',
        floor:'Ground Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306028', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Electical Network Analysis', 
        examTime: '10:00 AM', 
        date:'03/06/2024',
        roomNumber: 'A101',
        block:'1',
        wing: 'A',
        floor:'Ground Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306029', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Electical Network Analysis', 
        examTime: '10:00 AM', 
        date:'03/06/2024',
        roomNumber: 'A101',
        block:'1',
        wing: 'A',
        floor:'Ground Floor',
        department: 'Electrical Department'
    },
    


    //BLOCK-2

    { 
        rollNumber: 'S221306030', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Microcontroller and Embedded Systems', 
        examTime: '10:00 AM', 
        date:'05/06/2024',
        roomNumber: 'A102',
        block:'2',
        wing: 'A',
        floor:'Ground Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306031', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Microcontroller and Embedded Systems', 
        examTime: '10:00 AM', 
        date:'05/06/2024',
        roomNumber: 'A102',
        block:'2',
        wing: 'A',
        floor:'Ground Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306032', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Electical Network Analysis', 
        examTime: '10:00 AM', 
        date:'03/06/2024',
        roomNumber: 'A101',
        block:'1',
        wing: 'A',
        floor:'Ground Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306033', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Microcontroller and Embedded Systems', 
        examTime: '10:00 AM', 
        date:'05/06/2024',
        roomNumber: 'A102',
        block:'2',
        wing: 'A',
        floor:'Ground Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306034', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Microcontroller and Embedded Systems', 
        examTime: '10:00 AM', 
        date:'05/06/2024',
        roomNumber: 'A102',
        block:'2',
        wing: 'A',
        floor:'Ground Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306035', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Microcontroller and Embedded Systems', 
        examTime: '10:00 AM', 
        date:'05/06/2024',
        roomNumber: 'A102',
        block:'2',
        wing: 'A',
        floor:'Ground Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306036', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Microcontroller and Embedded Systems', 
        examTime: '10:00 AM', 
        date:'05/06/2024',
        roomNumber: 'A102',
        block:'2',
        wing: 'A',
        floor:'Ground Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306037', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Microcontroller and Embedded Systems', 
        examTime: '10:00 AM', 
        date:'05/06/2024',
        roomNumber: 'A102',
        block:'2',
        wing: 'A',
        floor:'Ground Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306038', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Microcontroller and Embedded Systems', 
        examTime: '10:00 AM', 
        date:'05/06/2024',
        roomNumber: 'A102',
        block:'2',
        wing: 'A',
        floor:'Ground Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306039', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Microcontroller and Embedded Systems', 
        examTime: '10:00 AM', 
        date:'05/06/2024',
        roomNumber: 'A102',
        block:'2',
        wing: 'A',
        floor:'Ground Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306040', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Microcontroller and Embedded Systems', 
        examTime: '10:00 AM', 
        date:'05/06/2024',
        roomNumber: 'A102',
        block:'2',
        wing: 'A',
        floor:'Ground Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306041', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Microcontroller and Embedded Systems', 
        examTime: '10:00 AM', 
        date:'05/06/2024',
        roomNumber: 'A102',
        block:'2',
        wing: 'A',
        floor:'Ground Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306042', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Microcontroller and Embedded Systems', 
        examTime: '10:00 AM', 
        date:'05/06/2024',
        roomNumber: 'A102',
        block:'2',
        wing: 'A',
        floor:'Ground Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306043', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Microcontroller and Embedded Systems', 
        examTime: '10:00 AM', 
        date:'05/06/2024',
        roomNumber: 'A102',
        block:'2',
        wing: 'A',
        floor:'Ground Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306044', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Microcontroller and Embedded Systems', 
        examTime: '10:00 AM', 
        date:'05/06/2024',
        roomNumber: 'A102',
        block:'2',
        wing: 'A',
        floor:'Ground Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306045', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Microcontroller and Embedded Systems', 
        examTime: '10:00 AM', 
        date:'05/06/2024',
        roomNumber: 'A102',
        block:'2',
        wing: 'A',
        floor:'Ground Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306046', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Microcontroller and Embedded Systems', 
        examTime: '10:00 AM', 
        date:'05/06/2024',
        roomNumber: 'A102',
        block:'2',
        wing: 'A',
        floor:'Ground Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306047', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Microcontroller and Embedded Systems', 
        examTime: '10:00 AM', 
        date:'05/06/2024',
        roomNumber: 'A102',
        block:'2',
        wing: 'A',
        floor:'Ground Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306048', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Microcontroller and Embedded Systems', 
        examTime: '10:00 AM', 
        date:'05/06/2024',
        roomNumber: 'A102',
        block:'2',
        wing: 'A',
        floor:'Ground Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306049', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Microcontroller and Embedded Systems', 
        examTime: '10:00 AM', 
        date:'05/06/2024',
        roomNumber: 'A102',
        block:'2',
        wing: 'A',
        floor:'Ground Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306050', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Microcontroller and Embedded Systems', 
        examTime: '10:00 AM', 
        date:'05/06/2024',
        roomNumber: 'A102',
        block:'2',
        wing: 'A',
        floor:'Ground Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306051', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Microcontroller and Embedded Systems', 
        examTime: '10:00 AM', 
        date:'05/06/2024',
        roomNumber: 'A102',
        block:'2',
        wing: 'A',
        floor:'Ground Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306052', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Microcontroller and Embedded Systems', 
        examTime: '10:00 AM', 
        date:'05/06/2024',
        roomNumber: 'A102',
        block:'2',
        wing: 'A',
        floor:'Ground Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306053', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Microcontroller and Embedded Systems', 
        examTime: '10:00 AM', 
        date:'05/06/2024',
        roomNumber: 'A102',
        block:'2',
        wing: 'A',
        floor:'Ground Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306054', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Microcontroller and Embedded Systems', 
        examTime: '10:00 AM', 
        date:'05/06/2024',
        roomNumber: 'A102',
        block:'2',
        wing: 'A',
        floor:'Ground Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306055', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Microcontroller and Embedded Systems', 
        examTime: '10:00 AM', 
        date:'05/06/2024',
        roomNumber: 'A102',
        block:'2',
        wing: 'A',
        floor:'Ground Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306056', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Microcontroller and Embedded Systems', 
        examTime: '10:00 AM', 
        date:'05/06/2024',
        roomNumber: 'A102',
        block:'2',
        wing: 'A',
        floor:'Ground Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306057', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Microcontroller and Embedded Systems', 
        examTime: '10:00 AM', 
        date:'05/06/2024',
        roomNumber: 'A102',
        block:'2',
        wing: 'A',
        floor:'Ground Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306058', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Microcontroller and Embedded Systems', 
        examTime: '10:00 AM', 
        date:'05/06/2024',
        roomNumber: 'A102',
        block:'2',
        wing: 'A',
        floor:'Ground Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306059', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Microcontroller and Embedded Systems', 
        examTime: '10:00 AM', 
        date:'05/06/2024',
        roomNumber: 'A102',
        block:'2',
        wing: 'A',
        floor:'Ground Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306060', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Microcontroller and Embedded Systems', 
        examTime: '10:00 AM', 
        date:'05/06/2024',
        roomNumber: 'A102',
        block:'2',
        wing: 'A',
        floor:'Ground Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306061', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Microcontroller and Embedded Systems', 
        examTime: '10:00 AM', 
        date:'05/06/2024',
        roomNumber: 'A102',
        block:'2',
        wing: 'A',
        floor:'Ground Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306062', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Microcontroller and Embedded Systems', 
        examTime: '10:00 AM', 
        date:'05/06/2024',
        roomNumber: 'A102',
        block:'2',
        wing: 'A',
        floor:'Ground Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306063', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Microcontroller and Embedded Systems', 
        examTime: '10:00 AM', 
        date:'05/06/2024',
        roomNumber: 'A102',
        block:'2',
        wing: 'A',
        floor:'Ground Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306064', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Microcontroller and Embedded Systems', 
        examTime: '10:00 AM', 
        date:'05/06/2024',
        roomNumber: 'A102',
        block:'2',
        wing: 'A',
        floor:'Ground Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306065', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Microcontroller and Embedded Systems', 
        examTime: '10:00 AM', 
        date:'05/06/2024',
        roomNumber: 'A102',
        block:'2',
        wing: 'A',
        floor:'Ground Floor',
        department: 'Electrical Department'
    },
   
    // BLOCK---3

    { 
        rollNumber: 'S221306066', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Power Electronics', 
        examTime: '10:00 AM', 
        date:'05/06/2024',
        roomNumber: 'A201',
        block:'3',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306067', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Power Electronics', 
        examTime: '10:00 AM', 
        date:'05/06/2024',
        roomNumber: 'A201',
        block:'3',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306068', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Power Electronics', 
        examTime: '10:00 AM', 
        date:'05/06/2024',
        roomNumber: 'A201',
        block:'3',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306069', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Power Electronics', 
        examTime: '10:00 AM', 
        date:'05/06/2024',
        roomNumber: 'A201',
        block:'3',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306070', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Power Electronics', 
        examTime: '10:00 AM', 
        date:'05/06/2024',
        roomNumber: 'A201',
        block:'3',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306071', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Power Electronics', 
        examTime: '10:00 AM', 
        date:'05/06/2024',
        roomNumber: 'A201',
        block:'3',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306072', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Power Electronics', 
        examTime: '10:00 AM', 
        date:'05/06/2024',
        roomNumber: 'A201',
        block:'3',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306073', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Power Electronics', 
        examTime: '10:00 AM', 
        date:'05/06/2024',
        roomNumber: 'A201',
        block:'3',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306074', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Power Electronics', 
        examTime: '10:00 AM', 
        date:'05/06/2024',
        roomNumber: 'A201',
        block:'3',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306075', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Power Electronics', 
        examTime: '10:00 AM', 
        date:'05/06/2024',
        roomNumber: 'A201',
        block:'3',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306076', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Power Electronics', 
        examTime: '10:00 AM', 
        date:'05/06/2024',
        roomNumber: 'A201',
        block:'3',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306077', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Power Electronics', 
        examTime: '10:00 AM', 
        date:'05/06/2024',
        roomNumber: 'A201',
        block:'3',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306078', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Power Electronics', 
        examTime: '10:00 AM', 
        date:'05/06/2024',
        roomNumber: 'A201',
        block:'3',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306079', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Power Electronics', 
        examTime: '10:00 AM', 
        date:'05/06/2024',
        roomNumber: 'A201',
        block:'3',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306080', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Power Electronics', 
        examTime: '10:00 AM', 
        date:'05/06/2024',
        roomNumber: 'A201',
        block:'3',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306081', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Power Electronics', 
        examTime: '10:00 AM', 
        date:'05/06/2024',
        roomNumber: 'A201',
        block:'3',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306082', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Power Electronics', 
        examTime: '10:00 AM', 
        date:'05/06/2024',
        roomNumber: 'A201',
        block:'3',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306083', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Power Electronics', 
        examTime: '10:00 AM', 
        date:'05/06/2024',
        roomNumber: 'A201',
        block:'3',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306084', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Power Electronics', 
        examTime: '10:00 AM', 
        date:'05/06/2024',
        roomNumber: 'A201',
        block:'3',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306085', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Power Electronics', 
        examTime: '10:00 AM', 
        date:'05/06/2024',
        roomNumber: 'A201',
        block:'3',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306086', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Power Electronics', 
        examTime: '10:00 AM', 
        date:'05/06/2024',
        roomNumber: 'A201',
        block:'3',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306087', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Power Electronics', 
        examTime: '10:00 AM', 
        date:'05/06/2024',
        roomNumber: 'A201',
        block:'3',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306088', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Power Electronics', 
        examTime: '10:00 AM', 
        date:'05/06/2024',
        roomNumber: 'A201',
        block:'3',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306089', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Power Electronics', 
        examTime: '10:00 AM', 
        date:'05/06/2024',
        roomNumber: 'A201',
        block:'3',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306090', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Power Electronics', 
        examTime: '10:00 AM', 
        date:'05/06/2024',
        roomNumber: 'A201',
        block:'3',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306091', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Power Electronics', 
        examTime: '10:00 AM', 
        date:'05/06/2024',
        roomNumber: 'A201',
        block:'3',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306092', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Power Electronics', 
        examTime: '10:00 AM', 
        date:'05/06/2024',
        roomNumber: 'A201',
        block:'3',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306093', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Power Electronics', 
        examTime: '10:00 AM', 
        date:'05/06/2024',
        roomNumber: 'A201',
        block:'3',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306094', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Power Electronics', 
        examTime: '10:00 AM', 
        date:'05/06/2024',
        roomNumber: 'A201',
        block:'3',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306095', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Power Electronics', 
        examTime: '10:00 AM', 
        date:'05/06/2024',
        roomNumber: 'A201',
        block:'3',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306096', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Power Electronics', 
        examTime: '10:00 AM', 
        date:'05/06/2024',
        roomNumber: 'A201',
        block:'3',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306097', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Power Electronics', 
        examTime: '10:00 AM', 
        date:'05/06/2024',
        roomNumber: 'A201',
        block:'3',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306098', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Power Electronics', 
        examTime: '10:00 AM', 
        date:'05/06/2024',
        roomNumber: 'A201',
        block:'3',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306099', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Power Electronics', 
        examTime: '10:00 AM', 
        date:'05/06/2024',
        roomNumber: 'A201',
        block:'3',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306100', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Power Electronics', 
        examTime: '10:00 AM', 
        date:'05/06/2024',
        roomNumber: 'A201',
        block:'3',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
   

    //BLOCK---4

    { 
        rollNumber: 'S221306101', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Power System Engineering', 
        examTime: '10:00 AM', 
        date:'10/06/2024',
        roomNumber: 'A202',
        block:'4',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306102', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Power System Engineering', 
        examTime: '10:00 AM', 
        date:'10/06/2024',
        roomNumber: 'A202',
        block:'4',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306103', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Power System Engineering', 
        examTime: '10:00 AM', 
        date:'10/06/2024',
        roomNumber: 'A202',
        block:'4',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306104', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Power System Engineering', 
        examTime: '10:00 AM', 
        date:'10/06/2024',
        roomNumber: 'A202',
        block:'4',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306105', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Power System Engineering', 
        examTime: '10:00 AM', 
        date:'10/06/2024',
        roomNumber: 'A202',
        block:'4',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306106', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Power System Engineering', 
        examTime: '10:00 AM', 
        date:'10/06/2024',
        roomNumber: 'A202',
        block:'4',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306107', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Power System Engineering', 
        examTime: '10:00 AM', 
        date:'10/06/2024',
        roomNumber: 'A202',
        block:'4',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306108', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Power System Engineering', 
        examTime: '10:00 AM', 
        date:'10/06/2024',
        roomNumber: 'A202',
        block:'4',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306109', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Power System Engineering', 
        examTime: '10:00 AM', 
        date:'10/06/2024',
        roomNumber: 'A202',
        block:'4',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306110', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Power System Engineering', 
        examTime: '10:00 AM', 
        date:'10/06/2024',
        roomNumber: 'A202',
        block:'4',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306111', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Power System Engineering', 
        examTime: '10:00 AM', 
        date:'10/06/2024',
        roomNumber: 'A202',
        block:'4',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306112', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Power System Engineering', 
        examTime: '10:00 AM', 
        date:'10/06/2024',
        roomNumber: 'A202',
        block:'4',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306113', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Power System Engineering', 
        examTime: '10:00 AM', 
        date:'10/06/2024',
        roomNumber: 'A202',
        block:'4',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306114', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Power System Engineering', 
        examTime: '10:00 AM', 
        date:'10/06/2024',
        roomNumber: 'A202',
        block:'4',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306115', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Power System Engineering', 
        examTime: '10:00 AM', 
        date:'10/06/2024',
        roomNumber: 'A202',
        block:'4',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306116', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Power System Engineering', 
        examTime: '10:00 AM', 
        date:'10/06/2024',
        roomNumber: 'A202',
        block:'4',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306117', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Power System Engineering', 
        examTime: '10:00 AM', 
        date:'10/06/2024',
        roomNumber: 'A202',
        block:'4',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306118', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Power System Engineering', 
        examTime: '10:00 AM', 
        date:'10/06/2024',
        roomNumber: 'A202',
        block:'4',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306119', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Power System Engineering', 
        examTime: '10:00 AM', 
        date:'10/06/2024',
        roomNumber: 'A202',
        block:'4',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306120', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Power System Engineering', 
        examTime: '10:00 AM', 
        date:'10/06/2024',
        roomNumber: 'A202',
        block:'4',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306121', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Power System Engineering', 
        examTime: '10:00 AM', 
        date:'10/06/2024',
        roomNumber: 'A202',
        block:'4',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306122', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Power System Engineering', 
        examTime: '10:00 AM', 
        date:'10/06/2024',
        roomNumber: 'A202',
        block:'4',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306123', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Power System Engineering', 
        examTime: '10:00 AM', 
        date:'10/06/2024',
        roomNumber: 'A202',
        block:'4',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306124', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Power System Engineering', 
        examTime: '10:00 AM', 
        date:'10/06/2024',
        roomNumber: 'A202',
        block:'4',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306125', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Power System Engineering', 
        examTime: '10:00 AM', 
        date:'10/06/2024',
        roomNumber: 'A202',
        block:'4',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306126', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Power System Engineering', 
        examTime: '10:00 AM', 
        date:'10/06/2024',
        roomNumber: 'A202',
        block:'4',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306127', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Power System Engineering', 
        examTime: '10:00 AM', 
        date:'10/06/2024',
        roomNumber: 'A202',
        block:'4',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306128', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Power System Engineering', 
        examTime: '10:00 AM', 
        date:'10/06/2024',
        roomNumber: 'A202',
        block:'4',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306129', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Power System Engineering', 
        examTime: '10:00 AM', 
        date:'10/06/2024',
        roomNumber: 'A202',
        block:'4',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306130', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Power System Engineering', 
        examTime: '10:00 AM', 
        date:'10/06/2024',
        roomNumber: 'A202',
        block:'4',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306131', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Power System Engineering', 
        examTime: '10:00 AM', 
        date:'10/06/2024',
        roomNumber: 'A202',
        block:'4',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306132', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Power System Engineering', 
        examTime: '10:00 AM', 
        date:'10/06/2024',
        roomNumber: 'A202',
        block:'4',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306133', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Power System Engineering', 
        examTime: '10:00 AM', 
        date:'10/06/2024',
        roomNumber: 'A202',
        block:'4',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306134', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Power System Engineering', 
        examTime: '10:00 AM', 
        date:'10/06/2024',
        roomNumber: 'A202',
        block:'4',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306135', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Power System Engineering', 
        examTime: '10:00 AM', 
        date:'10/06/2024',
        roomNumber: 'A202',
        block:'4',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306136', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Power System Engineering', 
        examTime: '10:00 AM', 
        date:'10/06/2024',
        roomNumber: 'A202',
        block:'4',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },

    // Faraday hall
    { 
        rollNumber: 'S221306137', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Design Thinking for Academic Project', 
        examTime: '10:00 AM', 
        date:'12/06/2024',
        roomNumber: 'Faraday Hall',
        block:'5',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306138', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Design Thinking for Academic Project', 
        examTime: '10:00 AM', 
        date:'12/06/2024',
        roomNumber: 'Faraday Hall',
        block:'5',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306139', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Design Thinking for Academic Project', 
        examTime: '10:00 AM', 
        date:'12/06/2024',
        roomNumber: 'Faraday Hall',
        block:'5',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306140', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Design Thinking for Academic Project', 
        examTime: '10:00 AM', 
        date:'12/06/2024',
        roomNumber: 'Faraday Hall',
        block:'5',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306141', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Design Thinking for Academic Project', 
        examTime: '10:00 AM', 
        date:'12/06/2024',
        roomNumber: 'Faraday Hall',
        block:'5',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306142', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Design Thinking for Academic Project', 
        examTime: '10:00 AM', 
        date:'12/06/2024',
        roomNumber: 'Faraday Hall',
        block:'5',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306143', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Design Thinking for Academic Project', 
        examTime: '10:00 AM', 
        date:'12/06/2024',
        roomNumber: 'Faraday Hall',
        block:'5',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306144', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Design Thinking for Academic Project', 
        examTime: '10:00 AM', 
        date:'12/06/2024',
        roomNumber: 'Faraday Hall',
        block:'5',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306145', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Design Thinking for Academic Project', 
        examTime: '10:00 AM', 
        date:'12/06/2024',
        roomNumber: 'Faraday Hall',
        block:'5',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306146', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Design Thinking for Academic Project', 
        examTime: '10:00 AM', 
        date:'12/06/2024',
        roomNumber: 'Faraday Hall',
        block:'5',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306147', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Design Thinking for Academic Project', 
        examTime: '10:00 AM', 
        date:'12/06/2024',
        roomNumber: 'Faraday Hall',
        block:'5',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306148', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Design Thinking for Academic Project', 
        examTime: '10:00 AM', 
        date:'12/06/2024',
        roomNumber: 'Faraday Hall',
        block:'5',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306149', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Design Thinking for Academic Project', 
        examTime: '10:00 AM', 
        date:'12/06/2024',
        roomNumber: 'Faraday Hall',
        block:'5',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    { 
        rollNumber: 'S221306150', 
        branch: 'Electrical Department', 
        semester: '4th', 
        subject: 'Design Thinking for Academic Project', 
        examTime: '10:00 AM', 
        date:'12/06/2024',
        roomNumber: 'Faraday Hall',
        block:'5',
        wing: 'A',
        floor:'First Floor',
        department: 'Electrical Department'
    },
    


];

examForm.addEventListener('submit', function(event) {
    event.preventDefault();
    const rollNumber = document.getElementById('rollNumber').value;
    const student = students.find(s => s.rollNumber === rollNumber);

    if (student) {
        // Display exam details
        resultDiv.classList.remove('hidden');
        branchDisplay.textContent = `Branch: ${student.branch}`;
        semesterDisplay.textContent = `Semester: ${student.semester}`;
        rollNumberDisplay.textContent = `Seat Number: ${student.rollNumber}`;
        subjectDisplay.textContent = `Subject: ${student.subject}`;
        examTimeDisplay.textContent = `Exam Time: ${student.examTime}`;
        datedisplay.textContent = `Date of Exam: ${student.date}`;
        roomNumberDisplay.textContent = `Room Number: ${student.roomNumber}`;
        blockdisplay.textContent = `Block Number: ${student.block}`;
        wingDisplay.textContent = `Wing: ${student.wing}`;
        floordisplay.textContent = `Floor: ${student.floor}`;
        departmentDisplay.textContent = `Department: ${student.department}`;
        
        // Hide error message
        errorDiv.classList.add('hidden');
        errorMessage.textContent = '';
    } else {
        // Display error message
        errorDiv.classList.remove('hidden');
        errorMessage.textContent = 'Invalid roll number. Please try again.';
        
        // Hide exam details
        resultDiv.classList.add('hidden');
        branchDisplay.textContent = '';
        semesterDisplay.textContent = '';
        rollNumberDisplay.textContent = '';
        subjectDisplay.textContent = '';
        examTimeDisplay.textContent = '';
        datedisplay.textContent='';
        roomNumberDisplay.textContent = '';
        blockdisplay.textContent='';
        wingDisplay.textContent = '';
        floordisplay.textContent='';
        departmentDisplay.textContent = '';
    }
});
